
name: Doxygen Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Generate documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: './'
          doxyfile-path: 'Documentation/Doxyfile'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './Documentation/html'
